// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messageproto.proto

package DistributedLocking;

public final class Messageproto {
  private Messageproto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DistributedLocking.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    java.util.List<DistributedLocking.Messageproto.Message.ClockPair> 
        getPairList();
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    DistributedLocking.Messageproto.Message.ClockPair getPair(int index);
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    int getPairCount();
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    java.util.List<? extends DistributedLocking.Messageproto.Message.ClockPairOrBuilder> 
        getPairOrBuilderList();
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    DistributedLocking.Messageproto.Message.ClockPairOrBuilder getPairOrBuilder(
        int index);

    /**
     * <code>required int32 ProcessID = 4;</code>
     */
    boolean hasProcessID();
    /**
     * <code>required int32 ProcessID = 4;</code>
     */
    int getProcessID();
  }
  /**
   * Protobuf type {@code DistributedLocking.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DistributedLocking.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      name_ = "";
      pair_ = java.util.Collections.emptyList();
      processID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pair_ = new java.util.ArrayList<DistributedLocking.Messageproto.Message.ClockPair>();
                mutable_bitField0_ |= 0x00000002;
              }
              pair_.add(
                  input.readMessage(DistributedLocking.Messageproto.Message.ClockPair.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              processID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pair_ = java.util.Collections.unmodifiableList(pair_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DistributedLocking.Messageproto.Message.class, DistributedLocking.Messageproto.Message.Builder.class);
    }

    public interface ClockPairOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DistributedLocking.Message.ClockPair)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 ProcessNumber = 1;</code>
       */
      boolean hasProcessNumber();
      /**
       * <code>required int32 ProcessNumber = 1;</code>
       */
      int getProcessNumber();

      /**
       * <code>required int32 Counter = 2;</code>
       */
      boolean hasCounter();
      /**
       * <code>required int32 Counter = 2;</code>
       */
      int getCounter();
    }
    /**
     * Protobuf type {@code DistributedLocking.Message.ClockPair}
     */
    public  static final class ClockPair extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:DistributedLocking.Message.ClockPair)
        ClockPairOrBuilder {
      // Use ClockPair.newBuilder() to construct.
      private ClockPair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ClockPair() {
        processNumber_ = 0;
        counter_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ClockPair(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                processNumber_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                counter_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_ClockPair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_ClockPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DistributedLocking.Messageproto.Message.ClockPair.class, DistributedLocking.Messageproto.Message.ClockPair.Builder.class);
      }

      private int bitField0_;
      public static final int PROCESSNUMBER_FIELD_NUMBER = 1;
      private int processNumber_;
      /**
       * <code>required int32 ProcessNumber = 1;</code>
       */
      public boolean hasProcessNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ProcessNumber = 1;</code>
       */
      public int getProcessNumber() {
        return processNumber_;
      }

      public static final int COUNTER_FIELD_NUMBER = 2;
      private int counter_;
      /**
       * <code>required int32 Counter = 2;</code>
       */
      public boolean hasCounter() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Counter = 2;</code>
       */
      public int getCounter() {
        return counter_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasProcessNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCounter()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, processNumber_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, counter_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, processNumber_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, counter_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof DistributedLocking.Messageproto.Message.ClockPair)) {
          return super.equals(obj);
        }
        DistributedLocking.Messageproto.Message.ClockPair other = (DistributedLocking.Messageproto.Message.ClockPair) obj;

        boolean result = true;
        result = result && (hasProcessNumber() == other.hasProcessNumber());
        if (hasProcessNumber()) {
          result = result && (getProcessNumber()
              == other.getProcessNumber());
        }
        result = result && (hasCounter() == other.hasCounter());
        if (hasCounter()) {
          result = result && (getCounter()
              == other.getCounter());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasProcessNumber()) {
          hash = (37 * hash) + PROCESSNUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getProcessNumber();
        }
        if (hasCounter()) {
          hash = (37 * hash) + COUNTER_FIELD_NUMBER;
          hash = (53 * hash) + getCounter();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DistributedLocking.Messageproto.Message.ClockPair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(DistributedLocking.Messageproto.Message.ClockPair prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code DistributedLocking.Message.ClockPair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:DistributedLocking.Message.ClockPair)
          DistributedLocking.Messageproto.Message.ClockPairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_ClockPair_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_ClockPair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DistributedLocking.Messageproto.Message.ClockPair.class, DistributedLocking.Messageproto.Message.ClockPair.Builder.class);
        }

        // Construct using DistributedLocking.Messageproto.Message.ClockPair.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          processNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          counter_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_ClockPair_descriptor;
        }

        public DistributedLocking.Messageproto.Message.ClockPair getDefaultInstanceForType() {
          return DistributedLocking.Messageproto.Message.ClockPair.getDefaultInstance();
        }

        public DistributedLocking.Messageproto.Message.ClockPair build() {
          DistributedLocking.Messageproto.Message.ClockPair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public DistributedLocking.Messageproto.Message.ClockPair buildPartial() {
          DistributedLocking.Messageproto.Message.ClockPair result = new DistributedLocking.Messageproto.Message.ClockPair(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.processNumber_ = processNumber_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.counter_ = counter_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DistributedLocking.Messageproto.Message.ClockPair) {
            return mergeFrom((DistributedLocking.Messageproto.Message.ClockPair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DistributedLocking.Messageproto.Message.ClockPair other) {
          if (other == DistributedLocking.Messageproto.Message.ClockPair.getDefaultInstance()) return this;
          if (other.hasProcessNumber()) {
            setProcessNumber(other.getProcessNumber());
          }
          if (other.hasCounter()) {
            setCounter(other.getCounter());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasProcessNumber()) {
            return false;
          }
          if (!hasCounter()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DistributedLocking.Messageproto.Message.ClockPair parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DistributedLocking.Messageproto.Message.ClockPair) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int processNumber_ ;
        /**
         * <code>required int32 ProcessNumber = 1;</code>
         */
        public boolean hasProcessNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 ProcessNumber = 1;</code>
         */
        public int getProcessNumber() {
          return processNumber_;
        }
        /**
         * <code>required int32 ProcessNumber = 1;</code>
         */
        public Builder setProcessNumber(int value) {
          bitField0_ |= 0x00000001;
          processNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 ProcessNumber = 1;</code>
         */
        public Builder clearProcessNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          processNumber_ = 0;
          onChanged();
          return this;
        }

        private int counter_ ;
        /**
         * <code>required int32 Counter = 2;</code>
         */
        public boolean hasCounter() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 Counter = 2;</code>
         */
        public int getCounter() {
          return counter_;
        }
        /**
         * <code>required int32 Counter = 2;</code>
         */
        public Builder setCounter(int value) {
          bitField0_ |= 0x00000002;
          counter_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 Counter = 2;</code>
         */
        public Builder clearCounter() {
          bitField0_ = (bitField0_ & ~0x00000002);
          counter_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:DistributedLocking.Message.ClockPair)
      }

      // @@protoc_insertion_point(class_scope:DistributedLocking.Message.ClockPair)
      private static final DistributedLocking.Messageproto.Message.ClockPair DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new DistributedLocking.Messageproto.Message.ClockPair();
      }

      public static DistributedLocking.Messageproto.Message.ClockPair getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<ClockPair>
          PARSER = new com.google.protobuf.AbstractParser<ClockPair>() {
        public ClockPair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ClockPair(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ClockPair> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ClockPair> getParserForType() {
        return PARSER;
      }

      public DistributedLocking.Messageproto.Message.ClockPair getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAIR_FIELD_NUMBER = 3;
    private java.util.List<DistributedLocking.Messageproto.Message.ClockPair> pair_;
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    public java.util.List<DistributedLocking.Messageproto.Message.ClockPair> getPairList() {
      return pair_;
    }
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    public java.util.List<? extends DistributedLocking.Messageproto.Message.ClockPairOrBuilder> 
        getPairOrBuilderList() {
      return pair_;
    }
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    public int getPairCount() {
      return pair_.size();
    }
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    public DistributedLocking.Messageproto.Message.ClockPair getPair(int index) {
      return pair_.get(index);
    }
    /**
     * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
     */
    public DistributedLocking.Messageproto.Message.ClockPairOrBuilder getPairOrBuilder(
        int index) {
      return pair_.get(index);
    }

    public static final int PROCESSID_FIELD_NUMBER = 4;
    private int processID_;
    /**
     * <code>required int32 ProcessID = 4;</code>
     */
    public boolean hasProcessID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 ProcessID = 4;</code>
     */
    public int getProcessID() {
      return processID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProcessID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPairCount(); i++) {
        if (!getPair(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < pair_.size(); i++) {
        output.writeMessage(3, pair_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, processID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < pair_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, pair_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, processID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DistributedLocking.Messageproto.Message)) {
        return super.equals(obj);
      }
      DistributedLocking.Messageproto.Message other = (DistributedLocking.Messageproto.Message) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && getPairList()
          .equals(other.getPairList());
      result = result && (hasProcessID() == other.hasProcessID());
      if (hasProcessID()) {
        result = result && (getProcessID()
            == other.getProcessID());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (getPairCount() > 0) {
        hash = (37 * hash) + PAIR_FIELD_NUMBER;
        hash = (53 * hash) + getPairList().hashCode();
      }
      if (hasProcessID()) {
        hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
        hash = (53 * hash) + getProcessID();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DistributedLocking.Messageproto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DistributedLocking.Messageproto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DistributedLocking.Messageproto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DistributedLocking.Messageproto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DistributedLocking.Messageproto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DistributedLocking.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DistributedLocking.Message)
        DistributedLocking.Messageproto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DistributedLocking.Messageproto.Message.class, DistributedLocking.Messageproto.Message.Builder.class);
      }

      // Construct using DistributedLocking.Messageproto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPairFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pairBuilder_ == null) {
          pair_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pairBuilder_.clear();
        }
        processID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DistributedLocking.Messageproto.internal_static_DistributedLocking_Message_descriptor;
      }

      public DistributedLocking.Messageproto.Message getDefaultInstanceForType() {
        return DistributedLocking.Messageproto.Message.getDefaultInstance();
      }

      public DistributedLocking.Messageproto.Message build() {
        DistributedLocking.Messageproto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DistributedLocking.Messageproto.Message buildPartial() {
        DistributedLocking.Messageproto.Message result = new DistributedLocking.Messageproto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (pairBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pair_ = java.util.Collections.unmodifiableList(pair_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pair_ = pair_;
        } else {
          result.pair_ = pairBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.processID_ = processID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DistributedLocking.Messageproto.Message) {
          return mergeFrom((DistributedLocking.Messageproto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DistributedLocking.Messageproto.Message other) {
        if (other == DistributedLocking.Messageproto.Message.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (pairBuilder_ == null) {
          if (!other.pair_.isEmpty()) {
            if (pair_.isEmpty()) {
              pair_ = other.pair_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePairIsMutable();
              pair_.addAll(other.pair_);
            }
            onChanged();
          }
        } else {
          if (!other.pair_.isEmpty()) {
            if (pairBuilder_.isEmpty()) {
              pairBuilder_.dispose();
              pairBuilder_ = null;
              pair_ = other.pair_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pairBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPairFieldBuilder() : null;
            } else {
              pairBuilder_.addAllMessages(other.pair_);
            }
          }
        }
        if (other.hasProcessID()) {
          setProcessID(other.getProcessID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasProcessID()) {
          return false;
        }
        for (int i = 0; i < getPairCount(); i++) {
          if (!getPair(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DistributedLocking.Messageproto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DistributedLocking.Messageproto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<DistributedLocking.Messageproto.Message.ClockPair> pair_ =
        java.util.Collections.emptyList();
      private void ensurePairIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pair_ = new java.util.ArrayList<DistributedLocking.Messageproto.Message.ClockPair>(pair_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DistributedLocking.Messageproto.Message.ClockPair, DistributedLocking.Messageproto.Message.ClockPair.Builder, DistributedLocking.Messageproto.Message.ClockPairOrBuilder> pairBuilder_;

      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public java.util.List<DistributedLocking.Messageproto.Message.ClockPair> getPairList() {
        if (pairBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pair_);
        } else {
          return pairBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public int getPairCount() {
        if (pairBuilder_ == null) {
          return pair_.size();
        } else {
          return pairBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public DistributedLocking.Messageproto.Message.ClockPair getPair(int index) {
        if (pairBuilder_ == null) {
          return pair_.get(index);
        } else {
          return pairBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder setPair(
          int index, DistributedLocking.Messageproto.Message.ClockPair value) {
        if (pairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairIsMutable();
          pair_.set(index, value);
          onChanged();
        } else {
          pairBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder setPair(
          int index, DistributedLocking.Messageproto.Message.ClockPair.Builder builderForValue) {
        if (pairBuilder_ == null) {
          ensurePairIsMutable();
          pair_.set(index, builderForValue.build());
          onChanged();
        } else {
          pairBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder addPair(DistributedLocking.Messageproto.Message.ClockPair value) {
        if (pairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairIsMutable();
          pair_.add(value);
          onChanged();
        } else {
          pairBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder addPair(
          int index, DistributedLocking.Messageproto.Message.ClockPair value) {
        if (pairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairIsMutable();
          pair_.add(index, value);
          onChanged();
        } else {
          pairBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder addPair(
          DistributedLocking.Messageproto.Message.ClockPair.Builder builderForValue) {
        if (pairBuilder_ == null) {
          ensurePairIsMutable();
          pair_.add(builderForValue.build());
          onChanged();
        } else {
          pairBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder addPair(
          int index, DistributedLocking.Messageproto.Message.ClockPair.Builder builderForValue) {
        if (pairBuilder_ == null) {
          ensurePairIsMutable();
          pair_.add(index, builderForValue.build());
          onChanged();
        } else {
          pairBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder addAllPair(
          java.lang.Iterable<? extends DistributedLocking.Messageproto.Message.ClockPair> values) {
        if (pairBuilder_ == null) {
          ensurePairIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pair_);
          onChanged();
        } else {
          pairBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder clearPair() {
        if (pairBuilder_ == null) {
          pair_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pairBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public Builder removePair(int index) {
        if (pairBuilder_ == null) {
          ensurePairIsMutable();
          pair_.remove(index);
          onChanged();
        } else {
          pairBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public DistributedLocking.Messageproto.Message.ClockPair.Builder getPairBuilder(
          int index) {
        return getPairFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public DistributedLocking.Messageproto.Message.ClockPairOrBuilder getPairOrBuilder(
          int index) {
        if (pairBuilder_ == null) {
          return pair_.get(index);  } else {
          return pairBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public java.util.List<? extends DistributedLocking.Messageproto.Message.ClockPairOrBuilder> 
           getPairOrBuilderList() {
        if (pairBuilder_ != null) {
          return pairBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pair_);
        }
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public DistributedLocking.Messageproto.Message.ClockPair.Builder addPairBuilder() {
        return getPairFieldBuilder().addBuilder(
            DistributedLocking.Messageproto.Message.ClockPair.getDefaultInstance());
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public DistributedLocking.Messageproto.Message.ClockPair.Builder addPairBuilder(
          int index) {
        return getPairFieldBuilder().addBuilder(
            index, DistributedLocking.Messageproto.Message.ClockPair.getDefaultInstance());
      }
      /**
       * <code>repeated .DistributedLocking.Message.ClockPair pair = 3;</code>
       */
      public java.util.List<DistributedLocking.Messageproto.Message.ClockPair.Builder> 
           getPairBuilderList() {
        return getPairFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DistributedLocking.Messageproto.Message.ClockPair, DistributedLocking.Messageproto.Message.ClockPair.Builder, DistributedLocking.Messageproto.Message.ClockPairOrBuilder> 
          getPairFieldBuilder() {
        if (pairBuilder_ == null) {
          pairBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DistributedLocking.Messageproto.Message.ClockPair, DistributedLocking.Messageproto.Message.ClockPair.Builder, DistributedLocking.Messageproto.Message.ClockPairOrBuilder>(
                  pair_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pair_ = null;
        }
        return pairBuilder_;
      }

      private int processID_ ;
      /**
       * <code>required int32 ProcessID = 4;</code>
       */
      public boolean hasProcessID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 ProcessID = 4;</code>
       */
      public int getProcessID() {
        return processID_;
      }
      /**
       * <code>required int32 ProcessID = 4;</code>
       */
      public Builder setProcessID(int value) {
        bitField0_ |= 0x00000004;
        processID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ProcessID = 4;</code>
       */
      public Builder clearProcessID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        processID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DistributedLocking.Message)
    }

    // @@protoc_insertion_point(class_scope:DistributedLocking.Message)
    private static final DistributedLocking.Messageproto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DistributedLocking.Messageproto.Message();
    }

    public static DistributedLocking.Messageproto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public DistributedLocking.Messageproto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedLocking_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedLocking_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedLocking_Message_ClockPair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedLocking_Message_ClockPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Messageproto.proto\022\022DistributedLocking" +
      "\"\224\001\n\007Message\022\014\n\004name\030\001 \002(\t\0223\n\004pair\030\003 \003(\013" +
      "2%.DistributedLocking.Message.ClockPair\022" +
      "\021\n\tProcessID\030\004 \002(\005\0323\n\tClockPair\022\025\n\rProce" +
      "ssNumber\030\001 \002(\005\022\017\n\007Counter\030\002 \002(\005B\016B\014Messa" +
      "geproto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DistributedLocking_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DistributedLocking_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedLocking_Message_descriptor,
        new java.lang.String[] { "Name", "Pair", "ProcessID", });
    internal_static_DistributedLocking_Message_ClockPair_descriptor =
      internal_static_DistributedLocking_Message_descriptor.getNestedTypes().get(0);
    internal_static_DistributedLocking_Message_ClockPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedLocking_Message_ClockPair_descriptor,
        new java.lang.String[] { "ProcessNumber", "Counter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
